### ISSUE TITLE
csvgrep needs an option to support tsvs as well

### ISSUE THREAD

**Issue by scottchiefbaker** [neilb/csvgrep#2]
I deal with data in both `.csv` and `.tsv`. It would be great if csvgrep was smart enough to know the difference.

**Comment by neilb** [comment]
Ok -- adding this now.

**Comment by neilb** [comment]
Seems to work ok.

Will be in 0.04 -- let me know how it works for you.

**Comment by scottchiefbaker** [comment]
I don't see 0.04 anywhere. Is it on a separate branch, or on master?

**Comment by neilb** [comment]
I just released it to CPAN and pushed to github.

**Comment by scottchiefbaker** [comment]
There it is.
