### ISSUE TITLE
Documentation Conflict

### ISSUE THREAD

**Issue by tolga-balci** [neilb/csvgrep#23]
Hi Neil,

I spotted conflicting information in csvgrepdocumentation.

In [CPAN](https://metacpan.org/dist/csvgrep/view/bin/csvgrep), you mentioned that the -i option is for case-insensitive search:

![image](https://user-images.githubusercontent.com/34794458/168821785-617e7c38-55f2-477f-9810-6418c58bf7dc.png)

However, in [ReadTheDocs.io](https://csvkit.readthedocs.io/en/latest/scripts/csvgrep.html), it is mentioned that the -i is for inverted-match:

![image](https://user-images.githubusercontent.com/34794458/168822037-32e3e8c7-0df2-44f3-86dc-7b9b8d8de4d6.png)

I think both documentations need to be clarified for two things:

- What the -i flag actually does,
- What option should be used for case-insensitive search, if there is one.

Thanks!
Tolga

**Comment by neilb** [comment]
The second example you gave is from a different tool, that is also called csvgrep :-)
