### ISSUE TITLE
Discussion: Would you consider an option to simply display a CSV (no grepping)

### ISSUE THREAD

**Issue by scottchiefbaker** [neilb/csvgrep#4]
For simplicity sometimes I just want to display a `.csv` as a table (no grepping) required. Currently the only way to do to this is:

```
csvgrep . books.csv
```

Where your grep pattern is something that matches everything. It would be nice if `csvgrep` displayed the full file if you did not specify a pattern match. Like:

```
csvgrep books.csv
```

Check if `@ARGV == 1` and that's it's a readable file and then just display it. Possibly output a "No pattern match specified, displaying entire file"

**Comment by scottchiefbaker** [comment]
Actually it turned out to be semi-simple. Something like this is what I was thinking: 

https://github.com/scottchiefbaker/csvgrep/blob/display_file/bin/csvgrep#L68

**Comment by neilb** [comment]
I *like* the idea of being able to just show the whole file. A general principle is that all features should work together, if at all possible. So this would have to let you also do the following:

    % csvgrep -d /var/csvlogs

And that would pick the latest CSV (or TSV) from that directory, and just show it all.

Using the '.' technique now works with and without the -d option.

Lemme think about it. Nudge me if I haven't done anything on this by sometime next week.

**Comment by scottchiefbaker** [comment]
Just pinging you on this issue.

**Comment by scottchiefbaker** [comment]
Back to ping again. Are you still out there?

**Comment by neilb** [comment]
Hi Scott -- still here, but been v busy with work and then off on holiday. I'll try to get to this soon!

Thanks for the nudge.

**Comment by neilb** [comment]
In the end I've decided not to do this, to maintain similarity with `grep`.
